export const copy = {
  en: {
    nav: {
      ariaLabel: "Primary navigation",
      features: "Features",
      pricing: "Pricing",
      waitlist: "Join waitlist",
      languageLabel: "Choose language",
    },
    hero: {
      eyebrow: "A planner that helps you think",
      headline: "Know what to do.",
      headlineAccent: "First.",
      intro: "Fokus sorts your tasks, shows you why, and nudges you when it is time to move.",
      join: "Join waitlist",
      demo: "See it in action",
      rerank: "Re-rank",
      previewLabel: "Animated preview of the Fokus task planner",
      taskListLabel: "Today’s prioritized tasks",
      analysisLabel: "AI task analysis",
      today: "FOKUS / TODAY",
      date: "Monday / 22 September",
      nextMoves: "Your next moves",
      updating: "AI is sorting things out...",
      synced: "Priorities are up to date",
      brief: "AI focus brief",
      analysisReady: "analysis ready",
      priorityScore: "priority score",
      basedOn: "from 6 signals",
      upside: "The upside",
      watchOut: "Keep in mind",
      priorityShift: "Priority changed",
      tasks: {
        proposal: { name: "Send proposal deck", time: "Today / 4:00 PM" },
        research: { name: "Check user feedback", time: "Tomorrow" },
        dentist: { name: "Book dentist", time: "Friday" },
      },
      scenarios: {
        proposal: {
          title: "Send proposal deck",
          meta: "Client work / Due in 2h 14m",
          upside: "Gets the client moving and keeps this week on track.",
          risk: "Needs 45 quiet minutes before your afternoon gets busy.",
          reminder: "Reminder set for 3:10 PM",
          signal: "The deadline got closer. Score is now 92.",
        },
        research: {
          title: "Check user feedback",
          meta: "Product work / 8 notes to review",
          upside: "Shows the biggest customer pain point before tomorrow’s planning.",
          risk: "Easy to overthink. Keep this review to 30 minutes.",
          reminder: "Reminder set for 10:30 AM",
          signal: "A new dependency showed up. Feedback moved to the top.",
        },
        dentist: {
          title: "Book dentist",
          meta: "Personal / Good slots are running out",
          upside: "Book now to grab the last good slot this week.",
          risk: "It is quick, but it may break your focus.",
          reminder: "Reminder set for 12:00 PM",
          signal: "Fewer slots are available. This task moved up.",
        },
      },
    },
    features: {
      title: "Less chaos. More clarity.",
      intro: "Fokus turns deadlines, effort, and impact into a task order you can change anytime.",
      mainTitle: "See why a task matters.",
      mainCopy: "See what you gain, what might get in the way, and why a task moved.",
      upside: "The upside",
      upsideCopy: "Moves the client decision forward before the deadline.",
      watchOut: "Keep in mind",
      watchOutCopy: "Needs quiet focus before your afternoon gets busy.",
      rows: [
        {
          title: "Pick the next task fast",
          copy: "Deadlines and dependencies update the list, so your next step stays clear.",
        },
        {
          title: "Reminders that show up on time",
          copy: "Get reminders in the app, email, or push before a task turns urgent.",
        },
        {
          title: "Find any task in seconds",
          copy: "Filter by status, due date, or priority without losing your plan.",
        },
      ],
    },
    pricing: {
      title: "Start free. Upgrade when you need more.",
      intro: "Simple plans for one person and a busy schedule. Cancel anytime.",
      billingLabel: "Billing period",
      monthly: "Monthly",
      annual: "Annual",
      save: "Save 20%",
      mostPopular: "Most popular",
      freeForever: "Free forever",
      billedMonthly: "Billed monthly",
      billedAnnually: "Billed annually",
      plans: [
        {
          name: "Solo",
          price: 0,
          yearlyPrice: 0,
          period: "month",
          description: [
            "Plan one clear day at a time.",
            "See what matters without extra setup.",
            "Change priorities whenever plans change.",
          ],
          features: ["AI task ranking", "In-app reminders", "Status and deadline filters"],
          buttonText: "Choose Solo",
          href: "#join",
        },
        {
          name: "Plus",
          price: 8,
          yearlyPrice: 6,
          period: "month",
          description: [
            "See why each task gets its rank.",
            "Get reminders through more channels.",
            "Handle busy weeks with stronger filters.",
          ],
          features: [
            "Everything in Solo",
            "Editable upside and watch-outs",
            "Email and push reminders",
            "Advanced priority filters",
          ],
          buttonText: "Choose Plus",
          href: "#join",
          isPopular: true,
        },
      ],
    },
    waitlist: {
      title: "Make your next step clear.",
      intro: "Join the waitlist for early access. Pick a plan and we’ll email you when Fokus is ready.",
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "you@example.com",
        plan: "Plan you want",
        submit: "Join waitlist",
        saving: "Saving your spot...",
        note: "No spam. Just launch news and a few product updates.",
        nameError: "Add your name first.",
        emailError: "Enter a valid email address.",
        successTitle: "You’re in!",
        successStart: "Thanks! We’ll send early access details to",
      },
    },
    footer: {
      first: "Fokus helps you decide what to do next.",
      second: "Built for clearer days.",
    },
  },
  id: {
    nav: {
      ariaLabel: "Navigasi utama",
      features: "Fitur",
      pricing: "Harga",
      waitlist: "Ikut waitlist",
      languageLabel: "Pilih bahasa",
    },
    hero: {
      eyebrow: "Planner yang bantu kamu berpikir",
      headline: "Kerjakan yang penting.",
      headlineAccent: "Duluan.",
      intro: "Fokus mengurutkan tugas, kasih alasannya, dan mengingatkan kamu saat waktunya mulai.",
      join: "Ikut waitlist",
      demo: "Lihat cara kerjanya",
      rerank: "Urutkan ulang",
      previewLabel: "Preview animasi planner tugas Fokus",
      taskListLabel: "Daftar tugas berdasarkan prioritas hari ini",
      analysisLabel: "Analisis tugas dari AI",
      today: "FOKUS / HARI INI",
      date: "Senin / 22 September",
      nextMoves: "Langkah berikutnya",
      updating: "AI lagi menyusun ulang...",
      synced: "Prioritas sudah diperbarui",
      brief: "Ringkasan fokus AI",
      analysisReady: "analisis siap",
      priorityScore: "skor prioritas",
      basedOn: "dari 6 sinyal",
      upside: "Manfaatnya",
      watchOut: "Perlu dicatat",
      priorityShift: "Prioritas berubah",
      tasks: {
        proposal: { name: "Kirim deck proposal", time: "Hari ini / 16.00" },
        research: { name: "Cek feedback pengguna", time: "Besok" },
        dentist: { name: "Buat janji dokter gigi", time: "Jumat" },
      },
      scenarios: {
        proposal: {
          title: "Kirim deck proposal",
          meta: "Kerja klien / Tenggat 2 jam 14 menit lagi",
          upside: "Bikin keputusan klien lanjut dan jadwal minggu ini tetap aman.",
          risk: "Butuh 45 menit fokus sebelum jadwal sore mulai penuh.",
          reminder: "Pengingat dipasang pukul 15.10",
          signal: "Deadline makin dekat. Skornya naik ke 92.",
        },
        research: {
          title: "Cek feedback pengguna",
          meta: "Kerja produk / 8 catatan untuk dicek",
          upside: "Menunjukkan masalah utama pengguna sebelum planning besok.",
          risk: "Gampang melebar. Batasi review ini sampai 30 menit.",
          reminder: "Pengingat dipasang pukul 10.30",
          signal: "Ada kebutuhan baru. Feedback naik ke urutan pertama.",
        },
        dentist: {
          title: "Buat janji dokter gigi",
          meta: "Pribadi / Jadwal yang enak mulai habis",
          upside: "Pesan sekarang supaya dapat slot terbaik minggu ini.",
          risk: "Cepat, tapi bisa memotong waktu fokusmu.",
          reminder: "Pengingat dipasang pukul 12.00",
          signal: "Slot makin sedikit. Tugas ini naik prioritas.",
        },
      },
    },
    features: {
      title: "Lebih tenang. Lebih jelas.",
      intro: "Fokus merapikan deadline, usaha, dan dampak jadi urutan tugas yang bisa kamu ubah kapan saja.",
      mainTitle: "Tahu kenapa tugas ini penting.",
      mainCopy: "Lihat manfaat, hambatan, dan alasan sebuah tugas naik prioritas.",
      upside: "Manfaatnya",
      upsideCopy: "Mendorong keputusan klien sebelum deadline.",
      watchOut: "Perlu dicatat",
      watchOutCopy: "Butuh fokus sebelum jadwal sore mulai penuh.",
      rows: [
        {
          title: "Cepat pilih tugas berikutnya",
          copy: "Deadline dan kebutuhan baru langsung memperbarui daftar, jadi langkah berikutnya tetap jelas.",
        },
        {
          title: "Pengingat yang datang tepat waktu",
          copy: "Dapatkan pengingat lewat aplikasi, email, atau push sebelum tugas jadi mendesak.",
        },
        {
          title: "Cari tugas dalam hitungan detik",
          copy: "Filter berdasarkan status, deadline, atau prioritas tanpa kehilangan rencanamu.",
        },
      ],
    },
    pricing: {
      title: "Mulai gratis. Upgrade saat butuh lebih.",
      intro: "Paket simpel untuk kamu dan jadwal yang padat. Bisa berhenti kapan saja.",
      billingLabel: "Periode tagihan",
      monthly: "Bulanan",
      annual: "Tahunan",
      save: "Hemat 20%",
      mostPopular: "Paling populer",
      freeForever: "Gratis selamanya",
      billedMonthly: "Ditagih bulanan",
      billedAnnually: "Ditagih tahunan",
      plans: [
        {
          name: "Solo",
          price: 0,
          yearlyPrice: 0,
          period: "bulan",
          description: [
            "Rencanakan satu hari dengan lebih jelas.",
            "Lihat yang penting tanpa setup ribet.",
            "Ubah prioritas saat rencana berubah.",
          ],
          features: ["Urutan tugas dari AI", "Pengingat di aplikasi", "Filter status dan deadline"],
          buttonText: "Pilih Solo",
          href: "#join",
        },
        {
          name: "Plus",
          price: 8,
          yearlyPrice: 6,
          period: "bulan",
          description: [
            "Tahu alasan di balik setiap prioritas.",
            "Dapatkan pengingat lewat lebih banyak channel.",
            "Atur minggu yang sibuk dengan filter lengkap.",
          ],
          features: [
            "Semua fitur Solo",
            "Analisis manfaat dan catatan yang bisa diedit",
            "Pengingat email dan push",
            "Filter prioritas lanjutan",
          ],
          buttonText: "Pilih Plus",
          href: "#join",
          isPopular: true,
        },
      ],
    },
    waitlist: {
      title: "Biar langkah berikutnya lebih jelas.",
      intro: "Ikut waitlist untuk akses awal. Pilih paket, nanti kami kabari lewat email saat Fokus siap.",
      form: {
        name: "Nama",
        namePlaceholder: "Nama kamu",
        email: "Email",
        emailPlaceholder: "kamu@contoh.com",
        plan: "Paket yang kamu mau",
        submit: "Ikut waitlist",
        saving: "Menyimpan tempatmu...",
        note: "Tanpa spam. Cuma kabar peluncuran dan sesekali update produk.",
        nameError: "Isi nama kamu dulu.",
        emailError: "Masukkan alamat email yang valid.",
        successTitle: "Kamu sudah masuk!",
        successStart: "Makasih! Detail akses awal akan kami kirim ke",
      },
    },
    footer: {
      first: "Fokus bantu kamu memilih apa yang perlu dikerjakan berikutnya.",
      second: "Biar hari terasa lebih jelas.",
    },
  },
} as const;

export type Locale = keyof typeof copy;
